services:
  upload_server_db:
    container_name: "upload-server"
    image: "bitnami/postgresql:latest"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
