services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
      - "./docker:/docker-entrypoint-initdb.d"
  app:
    build: .
    depends_on:
      - db
    restart: always
    container_name: upload-server
    ports:
      - 3000:3333
    env_file: .env

volumes:
  db:
